print('Hello World!')
print('What is your Name?')
myName = input()
print('It\'s good to meet you ' + myName)
print()
print('The length of your name is: ')
print(len(myName))
print('What is your age?')
myAge = input()
print('You will be ' + str(int(myAge) + 1 ) + ' in a year')

